jobs:
- job: build
  pool: Default
  # The Windows 7 update process is _very_ slow
  timeoutInMinutes: 240
  strategy:
    maxParallel: 4
    matrix: 
      windows_7:
        template: windows_7
      windows_10:
        template: windows_10
      windows_2019_docker:
        template: windows_2019_docker
      windows_2019:
        template: windows_2019
  steps:
  # Data is cached in $(Agent.BuildDirectory), which is not cleaned on every checkout.
  - bash: |
      lsb_release -a
      uname -r
      qemu-system-x86_64 --version
      packer --version
    displayName: Dump OS, kernel, qemu, packer version
  - bash: |
      if groups | grep -q "\bkvm\b"
      then
        echo "The user $(whoami) is a member of the kvm group"
        exit 0
      else
        echo "Please add $(whoami) to the kvm  group by running sudo usermod -aG kvm $(whoami)"
        exit -1
      fi
    displayName: Check kvm permissions
  - bash: |
      wget -nv -nc https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso -O $(Agent.BuildDirectory)/virtio-win.iso
    displayName: Download virtio-win iso
    continueOnError: true
  - bash: |
      export PACKER_LOG=1
      export PACKER_CACHE_DIR=$(Agent.BuildDirectory)/packer_cache/
      packer build --only=qemu --var virtio_win_iso=$(Agent.BuildDirectory)/virtio-win.iso $(template).json
      mkdir -p box/$(template)/
      mv $(template)_libvirt.box box/$(template)
    displayName: Build box
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.SourcesDirectory)/box
      artifactName: box
    # Don't waste too much time uploading artifacts on slow connections
    timeoutInMinutes: 30