jobs:
- job: build
  pool: Default
  strategy:
    maxParallel: 2
    matrix: 
      windows_7:
        template: windows_7
      windows_10:
        template: windows_10
      windows_2019:
        template: windows_2019
  steps:
  # Data is cached in $(Agent.BuildDirectory), which is not cleaned on every checkout.
  - bash: |
      wget -nv -nc https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso -O $(Agent.BuildDirectory)/virtio-win.iso
    displayName: Download virtio-win iso
    continueOnError: true
  - bash: |
      export PACKER_LOG=1
      export PACKER_CACHE_DIR=$(Agent.BuildDirectory)/packer_cache/
      packer build --only=qemu --var virtio_win_iso=$(Agent.BuildDirectory)/virtio-win.iso $(template).json
    displayName: Build box
