jobs:
- job: build
  pool: Default
  strategy:
    maxParallel: 2
    matrix: 
      windows_7:
        template: windows_7
      windows_10:
        template: windows_10
      windows_2019:
        template: windows_2019
  steps:
  - bash: |
      wget -nv -nc https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso -O virtio-win.iso
    displayName: Download virtio-win iso
  - bash: |
      packer build --only=qemu $(template).json
    displayName: Build box
